### ISSUE TITLE
Suspicious type cast in k-means++ initialization

### ISSUE THREAD

**Issue by rreusser** [cmtt/kmpp#6]
https://github.com/cmtt/kmpp/blob/b579100d12ea37fbd7128a15bae0c17c3101af2c/kmpp.js#L256-L265

On line 257, it looks like k-means++ initialization computes a random number from `0` to `DSum` and then floors it (via `~~`) to an integer. `rndVal` is only used in comparison to other distances. This seems strange since I don't see any particular connection between distances and integers. If things were normalized, that would be different, but if distances are on the order of ~1e-3 and n ~ 1000, won't `rndVal` always be ~0? Is it possible this is a typo?

**Comment by cmtt** [comment]
Hello @rreusser, thank you for opening this issue.

I think that the assumption is correct, casting the distance to an integer is not necessary, given that [distance](https://github.com/cmtt/kmpp/blob/b579100d12ea37fbd7128a15bae0c17c3101af2c/kmpp.js#L65) also doesn't return integers. 

Can you create a PR in order to address it?

It makes sense to address your PR #4 also very soon in order to get this project up to date.

**Comment by cmtt** [comment]
Hello @rreusser, merged #4 into `master` and addressed this issue. I will deploy a new version soon.

**Comment by rreusser** [comment]
Awesome, thanks soo much! Sorry I was away from the computer for a few days and time to devote to open source has been more and more sparse these days. I really, really appreciate it!

**Comment by cmtt** [comment]
Story of my life. The updated version has been released as of June 3rd.
